data_ingestion:
  bucket_name: hotel_reservation_info
  bucket_file_name: hotel_reservations.csv

data_preprocessing:
  skewed_features:
    - no_of_special_requests
    - avg_price_per_room
    - no_of_weekend_nights
  encoding:
    label_encoding:
      - booking_status
    ohe_hot_encoding:
      - type_of_meal_plan
      - room_type_reserved
      - market_segment_type
  drop_multicollinearity_columns:
    - market_segment_type_Online

